# Generated by Django 4.1.2 on 2022-10-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellocationmodel',
            name='hotel_email',
            field=models.EmailField(blank=True, default=0, max_length=254),
        ),
    ]
